title: 'strbckr.github.io'
description: "Carter Richard's personal Github pages website."
baseurl:
url: "https://strbckr.github.io"

header_pages:
  - index.md
  - about.md
  - projects.md
  - calendar.md

style: dark

footer: 'Follow me on <a href="https://github.com/strbckr">github</a>.'

# Build settings
markdown: kramdown
remote_theme:  b2a3e8/jekyll-theme-console

google_analytics: G-WLW268MS29

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag