title: 'strbckr.github.io'
description: "Carter Richard's personal Github pages website."
baseurl:
url: "https://strbckr.github.io"

header_pages:
  - index.md

style: dark

footer: 'Hello world!'

# Build settings
markdown: kramdown
remote_theme:  b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag